---
- name: intranet services
  hosts: all
  become: yes
  vars:
    index_text: "default text !\n"
  tasks:

    - block:
      - name : latest httpd version installed
        yum:
          name: httpd
          state: latest

      - name : latest firewallds version installed
        yum:
          name: firewalld
          state: latest

    - block:
      - name : firewalld permits http service
        firewalld:
          service: http
          permanent: true
          state: enabled
          immediate: yes
     
    - block:
      - name: httpd enabled and running
        service:
          name: httpd
          enabled: true
          state: started

      - name: firewalld enabled and running
        service:
          name: firewalld
          enabled: true
          state: started

    - block:
      - name: test html page
        copy:
          content: "{{ index_text }}"
          dest: /var/www/html/index.html

...
