---
- name: intranet services
  hosts: all
  become: yes

  tasks:
    - block:
      - name: test html page
        copy:
          content: "Welcome to the ansible test page !\n"
          dest: /etc/motd

...
