---
- name : latest httpd version installed
  yum:
    name: httpd
    state: latest

- name : latest firewallds version installed
  yum:
    name: firewalld
    state: latest

- name : firewalld permits http service
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
     
- name : firewalld permits httpservice
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: yes
     
- name: httpd enabled and running
  service:
    name: httpd
    enabled: true
    state: started

- name: firewalld enabled and running
  service:
    name: firewalld
    enabled: true
    state: started

- name: create test html page
  copy:
    content: "{{ index_text }} - updated on {{ ansible_date_time.iso8601 }} "
    dest: /var/www/html/index.html

...
